//
// Created by yazda on 6/13/2019.
//

#ifndef SCAN_LANG_DEFS_H
#define SCAN_LANG_DEFS_H

enum CX_TOKENS {
    ID, NUM, LPAREN, RPAREN, LBRACE, RBRACE, RETURN, IF,
    ELSE, WHILE, PRINTLN, WAIN, BECOMES, INT, EQ, NE, LT,
    GT, LE, GE, PLUS, MINUS, STAR, SLASH, PCT, COMMA, SEMI,
    NEW, DELETE, LBRACK, RBRACK, AMP, NULL, ZERO
};

enum CX_WHITESPACE {
    SPACE, TAB, NEWLINE, COMMENT, WHITESPACE
};

#endif //SCAN_LANG_DEFS_H
