from os import walk
from os.path import join

# TODO : The FUNDAMENTAL FIVE !!!!!
top_src = 'src'
includes=['include']
binaries=['scan']
objects=[]

# TODO : Later add this code to a separate python module
def fetch_src_files(top_src):
    farray = []
    for (dirpath, dirnames, filenames) in walk(top_src):
        for f in filenames:
            if f.endswith('.c'):
                farray.append(join(dirpath, f))
    return farray
def find_include_dirs(top_src):
    darray = []
    for (dirpath, dirnames, filenames) in walk(top_src):
        for f in filenames:
            if f.endswith('.h'):
                darray.append(dirpath)
                break
    return darray 

env = Environment(CPPPATH = find_include_dirs(top_src))

env.Program(target = 'scan', source = fetch_src_files(top_src))

